#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : procmail
Version  : 3.24
Release  : 13
URL      : https://mirrors.kernel.org/debian/pool/main/p/procmail/procmail_3.24.orig.tar.gz
Source0  : https://mirrors.kernel.org/debian/pool/main/p/procmail/procmail_3.24.orig.tar.gz
Summary  : procmail mail delivery agent
Group    : Development/Tools
License  : GPL-2.0
Requires: procmail-bin = %{version}-%{release}
Requires: procmail-license = %{version}-%{release}
Requires: procmail-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: mandir.patch

%description
Most mail servers such as sendmail need to have a local delivery agent.
Procmail can be used as the local delivery agent for you mail server.  It
supports a rich command set that allows you to pre-sort, archive, or re-mail
incoming mail automatically.  SmartList also needs procmail to operate.

%package bin
Summary: bin components for the procmail package.
Group: Binaries
Requires: procmail-license = %{version}-%{release}

%description bin
bin components for the procmail package.


%package license
Summary: license components for the procmail package.
Group: Default

%description license
license components for the procmail package.


%package man
Summary: man components for the procmail package.
Group: Default

%description man
man components for the procmail package.


%prep
%setup -q -n procmail-3.24
cd %{_builddir}/procmail-3.24
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1674080338
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1674080338
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/procmail
cp %{_builddir}/procmail-%{version}/COPYING %{buildroot}/usr/share/package-licenses/procmail/aac97ddcbe9232a375d87b7f09a54a9674fc8175 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/formail
/usr/bin/lockfile
/usr/bin/mailstat
/usr/bin/procmail

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/procmail/aac97ddcbe9232a375d87b7f09a54a9674fc8175

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/formail.1
/usr/share/man/man1/lockfile.1
/usr/share/man/man1/mailstat.1
/usr/share/man/man1/procmail.1
/usr/share/man/man5/procmailex.5
/usr/share/man/man5/procmailrc.5
/usr/share/man/man5/procmailsc.5
